level_1=[
    'xxxxxxxxxxxxxxxxxxxxxxxxx',
    'xP xxxxxxx   T      xxxxx',
    'x  xxxxxxx  xxxxxx  xxxxx',
    'x       xx  xxxxxx  xxxxx',
    'x       xx  xxx        xx',
    'x  xxx  xx  xxx      T xx',
    'x  xxx  xx  xx      xxxxx',
    'x  xxx  xx          xxxxx',
    'x  xxx        xxxx Exxxxx',
    'x  xxx  xxxxxxxxxx      x',
    'x         xxxxxxxxxxx  xx',
    'x    T           xxxxx  x',
    'xxx  xxxxxxx            x',
    'xxx  xxxxxxx  x         x',
    'x         xx  x      xxxx',
    'xxxE                    x',
    'xxx         xxxxxxxxxxxxx',
    'xxx  xxxxx  xxxxxxxxxxxxx',
    'xxx  xxxxx              x',
    'xx   xxxxx     T        x',
    'xx   xxxxxxxxxxxxx  xxxxx',
    'xx   T xxxxxxxxxxx  xxxxx',
    'xx          xxxx        x',
    'xxxx                    x',
    'xxxxxxxxxxxxxxxxxxxxxxxxx'
]

level_2=[
    'XXXXXXXXXXXXXXXXXXXXXXXXX',
    'XP      X         X     X',
    'X XXXXX XXXXXXXXX X XXX X',
    'X X     X     T   X E   X',
    'X X XXXXX XXX XXX XXXXX X',
    'X X     X X   X X       X',
    'X XXXXX X X X X XXXXXXX X',
    'X     X   X X X       X X',
    'X XXX X X XXX XXX XXXXX X',
    'X  EX X X XT            X',
    'X XXX X X XXXXXXXXXXX X X',
    'X X   X X             X X',
    'X X XXXXXXXXXXXXXXX X X X',
    'X X           T     X X X',
    'X XXXXXXXXXXXXXXXXX X X X',
    'X                   X X X',
    'X XXXXXXXXXXXXXXXXX XXX X',
    'X           X           X',
    'X XXXXXXXXX X XXX XXXXXXX',
    'X X       X X X   X     X',
    'X X XXXXX X X XXX X XXX X',
    'X X X T X     X X   X X X',
    'X X X X X XXXXX X X X X X',
    'X X X X   X     X X X X X',
    'X X XXXXX X XXXXX X X X X',
    'X X               X T X X',
    'XXXXXXXXXXXXXXXXXXXXXXXXX'

]

level_3 = [
    'xxxxxxxxxxxxxxxxxxxxx',
    'xP      x     x   x x',
    'x xxxxx x xxx x x x x',
    'x x   x   T x   x x x',
    'x x   x     x   x x x',
    'x x x   x x     E x x',
    'x x x x xxx xxxxxxx x',
    'x T x x   x   x   x x',
    'xxx x xxx xxx x x x x',
    'x   x   x x   T x   x',
    'x xxxxx x x xxx x xxx',
    'x E x   x x x   x   x',
    'xxx x x x xxx xxx x x',
    'x   x x x   x x   x x',
    'x xxx x x x x x x T x',
    'x x   x x x   x   x x',
    'xxx xxx xxxxxxxxxxx x',
    'x   x x x         x x',
    'x xxx x x xxxxxxx x x',
    'x E   x   x     T x x',
    'xxxxxxxxxxxxxxxxxxxxx'
]

level_4 = [
    'xxxxxxxxxxxxxxxxxxxxxxxxx',
    'xP            x      T  x',
    'x xxxxxxxxx x x xxx xxxxx',
    'x x x       x   x       x',
    'xxx xxx xxx xxx x xxxxxxx',
    'x     x   x   x x   E   x',
    'x xxx xxx xxxxxxx xxxxxxx',
    'x   x x x       x     x x',
    'xxxxx x xxx x x xxx xxx x',
    'x x x T   x xE  x x   x x',
    'x x x x xxxxx xxxxxxx xxx',
    'x x x   x  x       T    x',
    'x x x xxxxx  xxxxxxxxxxxx',
    'x   x   x          E    x',
    'xxx x x x xxxxxxxxx xxx x',
    'x   x x  T  x x     x   x',
    'x xxx xxx xxx xxxxxxx x x',
    'x   x x   x     x     x x',
    'xxx xxx xxx   x       xxx',
    'x   x   x   x  E    x x x',
    'xxxxxxx x xxx x x xxx x x',
    'x   x   x   x x x   x   x',
    'x x xxx xxx xxx xxx xxx x',
    'x x       x     x   x T x',
    'xxxxxxxxxxxxxxxxxxxxxxxxx'
]

level_5 = [
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xP  x     x   x   E   x       x',
    'xxx x xxxxx   x x xxx xxxxx x x',
    'x    T                        x',
    'x xxxxx x x xxxxx  xxx  xxxxx x',
    'x               x   xx   x    x',
    'xxxx  x xxxxxxx xxx xxxxx xxx x',
    'x x   x   x     x   x x    T  x',
    'x x xT      x xxxxx x x x xxxxx',
    'x   x  x  x x     x   x x     x',
    'x xxx  x  E x  xx xxxxx x xxx x',
    'x   x  x  x x   x x     x   x x',
    'xxx x xxx x x   x x xxxxx   x x',
    'x x x      x    x   x    E  x x',
    'x x x x x  T  xxxxxxx xxx xxx x',
    'x x x x x     x     x x x   x x',
    'x x xxx x xxxxxxx x x x xxx xxx',
    'x x     x x       x x     x   x',
    'x xxxxxxx xx  xxxxx xxxxxxxxx x',
    'x     E       x              Tx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
]

glevel = [level_1, level_2, level_3, level_4, level_5]
